apiVersion: v1
kind: Service
metadata:
  name: client-service
  namespace: "2401093"
spec:
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30007
  type: NodePort